// GENERATED by scripts/gen_bridge_contract.py; do not edit.
pub const VERSION: u16 = 1;
pub const HEADER_BYTES: usize = 96;
pub const MAX_PAYLOAD_BYTES: u64 = 33554432;
pub const MAX_PIXELS: u64 = 16777216;
pub const MAX_DIMENSION: u64 = 8192;
pub const PIXEL_FORMAT_MONO8_LEGACY: u64 = 0;
pub const PIXEL_FORMAT_MONO8: u64 = 17301505;
pub const PIXEL_FORMAT_RGB8: u64 = 35127316;
pub const MAX_PULL_KIND: u32 = 6;
pub const JSON_TRANSPORT_VERSION: u32 = 1;
pub const MAX_EVENT_TEXT_BYTES: usize = 4096;
