// GENERATED by scripts/gen_bridge_contract.py; do not edit.
pub const VERSION: u16 = 1;
pub const HEADER_BYTES: usize = 96;
pub const MAX_PAYLOAD_BYTES: u64 = 33554432;
pub const MAX_PIXELS: u64 = 16777216;
pub const MAX_DIMENSION: u64 = 8192;
