// GENERATED by scripts/gen_bridge_contract.py from review-contract.json; do not edit.
pub const PIXEL_FORMAT_MONO8_LEGACY: u64 = 0;
pub const PIXEL_FORMAT_MONO8: u64 = 17301505;
pub const PIXEL_FORMAT_RGB8: u64 = 35127316;
pub const PULL_KIND_REVIEW: u32 = 3;
pub const PULL_KIND_REVIEW_THUMBNAILS: u32 = 5;
pub const PULL_KIND_REVIEW_SERIES: u32 = 6;
