// Explicit timestamp semantics (issue #368).
//
// A bare uint64 timestamp cannot say which clock it came from, what one tick
// means, what instant it marks, or whether it is valid. Every producer of
// `Frame::timestamp` now publishes a TimestampDescriptor for its session and
// every consumer that converts or subtracts timestamps goes through the
// checked helpers here. Nanosecond normalization happens only at these
// documented boundaries; raw device ticks are preserved alongside for audit.
#pragma once

#include <cstdint>
#include <optional>
#include <string>

namespace camera::common {

enum class ClockDomain {
    Unknown,          // legacy / undeclared
    DeviceTicks,      // camera-internal counter (not comparable to host clocks)
    HostMonotonicUs,  // Tools::getTimestamp() domain (QPC / steady, microseconds)
    HostSteadyNs,     // std::chrono::steady_clock nanoseconds (mock camera)
    HostWallClockNs,  // system_clock nanoseconds since epoch
};

enum class TimestampSemantic {
    Unknown,
    DeviceExposureStart, // sensor exposure start
    DeviceCapture,       // device-reported capture/acquisition instant (MindVision uiTimeStamp)
    TransportReceipt,    // frame grabber / SDK buffer completion (EGrabber BUFFER_INFO_TIMESTAMP)
    HostReceipt,         // host thread dequeued the frame (CaptureService hostTimestampUs)
    Synthetic,           // generated by a simulated source (mock camera)
};

enum class TimestampValidity {
    Valid,
    Unavailable, // this source never provides one
    Unsupported, // provided but of unknown meaning (legacy)
    Error,       // read failed for this frame/session
};

inline const char* toString(ClockDomain d)
{
    switch (d) {
    case ClockDomain::Unknown: return "unknown";
    case ClockDomain::DeviceTicks: return "deviceTicks";
    case ClockDomain::HostMonotonicUs: return "hostMonotonicUs";
    case ClockDomain::HostSteadyNs: return "hostSteadyNs";
    case ClockDomain::HostWallClockNs: return "hostWallClockNs";
    }
    return "unknown";
}
inline const char* toString(TimestampSemantic s)
{
    switch (s) {
    case TimestampSemantic::Unknown: return "unknown";
    case TimestampSemantic::DeviceExposureStart: return "deviceExposureStart";
    case TimestampSemantic::DeviceCapture: return "deviceCapture";
    case TimestampSemantic::TransportReceipt: return "transportReceipt";
    case TimestampSemantic::HostReceipt: return "hostReceipt";
    case TimestampSemantic::Synthetic: return "synthetic";
    }
    return "unknown";
}
inline const char* toString(TimestampValidity v)
{
    switch (v) {
    case TimestampValidity::Valid: return "valid";
    case TimestampValidity::Unavailable: return "unavailable";
    case TimestampValidity::Unsupported: return "unsupported";
    case TimestampValidity::Error: return "error";
    }
    return "unknown";
}

inline ClockDomain clockDomainFromString(const std::string& s)
{
    if (s == "deviceTicks") return ClockDomain::DeviceTicks;
    if (s == "hostMonotonicUs") return ClockDomain::HostMonotonicUs;
    if (s == "hostSteadyNs") return ClockDomain::HostSteadyNs;
    if (s == "hostWallClockNs") return ClockDomain::HostWallClockNs;
    return ClockDomain::Unknown;
}
inline TimestampSemantic timestampSemanticFromString(const std::string& s)
{
    if (s == "deviceExposureStart") return TimestampSemantic::DeviceExposureStart;
    if (s == "deviceCapture") return TimestampSemantic::DeviceCapture;
    if (s == "transportReceipt") return TimestampSemantic::TransportReceipt;
    if (s == "hostReceipt") return TimestampSemantic::HostReceipt;
    if (s == "synthetic") return TimestampSemantic::Synthetic;
    return TimestampSemantic::Unknown;
}
inline TimestampValidity timestampValidityFromString(const std::string& s)
{
    if (s == "valid") return TimestampValidity::Valid;
    if (s == "unavailable") return TimestampValidity::Unavailable;
    if (s == "unsupported") return TimestampValidity::Unsupported;
    return TimestampValidity::Error;
}

// Describes the `Frame::timestamp` field of one acquisition session.
struct TimestampDescriptor {
    static constexpr uint32_t kSchemaVersion = 1;
    ClockDomain domain{ClockDomain::Unknown};
    // Ticks per second of the value stored in Frame::timestamp (after the
    // adapter's documented normalization). 0 = unknown.
    uint64_t ticksPerSecond{0};
    // Native tick rate of the device counter the value was derived from
    // (0 when the value is native / not derived). Preserved for audit.
    uint64_t nativeTicksPerSecond{0};
    TimestampSemantic semantic{TimestampSemantic::Unknown};
    TimestampValidity validity{TimestampValidity::Unsupported};
    // Counter width in bits for wrap analysis (0 = unknown / no wrap).
    uint32_t counterBits{0};
    // Acquisition session the descriptor belongs to (0 = unknown).
    uint64_t sessionGeneration{0};

    bool isValid() const { return validity == TimestampValidity::Valid && ticksPerSecond > 0; }
    bool comparableTo(const TimestampDescriptor& o) const
    {
        return isValid() && o.isValid() && domain == o.domain && domain != ClockDomain::Unknown &&
               domain != ClockDomain::DeviceTicks ? true
               : (isValid() && o.isValid() && domain == o.domain &&
                  domain == ClockDomain::DeviceTicks && sessionGeneration == o.sessionGeneration &&
                  sessionGeneration != 0);
    }
};

// One timestamp plus the descriptor needed to interpret it.
struct TimestampValue {
    uint64_t rawTicks{0};
    TimestampDescriptor descriptor{};

    // Checked conversion to nanoseconds. Empty when the descriptor is not
    // valid or the multiplication would overflow.
    std::optional<uint64_t> toNanoseconds() const
    {
        if (!descriptor.isValid()) return std::nullopt;
        const uint64_t tps = descriptor.ticksPerSecond;
        if (tps == 1'000'000'000ULL) return rawTicks;
        if (tps < 1'000'000'000ULL && (1'000'000'000ULL % tps) == 0) {
            const uint64_t mul = 1'000'000'000ULL / tps;
            if (rawTicks > UINT64_MAX / mul) return std::nullopt;
            return rawTicks * mul;
        }
        // Non-integer ratio: use 128-bit-safe two-step arithmetic.
        const uint64_t seconds = rawTicks / tps;
        const uint64_t rem = rawTicks % tps;
        if (seconds > UINT64_MAX / 1'000'000'000ULL) return std::nullopt;
        const uint64_t base = seconds * 1'000'000'000ULL;
        const uint64_t frac = (rem * 1'000'000'000ULL) / tps; // rem < tps, safe when tps <= 2^34
        if (base > UINT64_MAX - frac) return std::nullopt;
        return base + frac;
    }
};

// Signed difference (a - b) in nanoseconds. Rejected (empty) unless both
// values are valid AND live in the same comparable clock domain — device tick
// counters are only comparable within one session. This is the only
// sanctioned way to subtract two timestamps.
inline std::optional<int64_t> differenceNs(const TimestampValue& a, const TimestampValue& b)
{
    if (!a.descriptor.comparableTo(b.descriptor)) return std::nullopt;
    const auto an = a.toNanoseconds();
    const auto bn = b.toNanoseconds();
    if (!an || !bn) return std::nullopt;
    if (*an >= *bn) {
        const uint64_t d = *an - *bn;
        if (d > static_cast<uint64_t>(INT64_MAX)) return std::nullopt;
        return static_cast<int64_t>(d);
    }
    const uint64_t d = *bn - *an;
    if (d > static_cast<uint64_t>(INT64_MAX)) return std::nullopt;
    return -static_cast<int64_t>(d);
}

// Wrap detection for a monotonically increasing device counter: true when
// the new raw value is smaller than the previous one by more than half the
// counter range (or any decrease when the width is unknown).
inline bool detectCounterWrap(uint64_t previousRaw, uint64_t currentRaw, uint32_t counterBits)
{
    if (currentRaw >= previousRaw) return false;
    if (counterBits == 0 || counterBits >= 64) return true;
    const uint64_t range = 1ULL << counterBits;
    return (previousRaw - currentRaw) > (range / 2);
}

// Human-readable, e.g. "deviceTicks @1e9 Hz (native 10000 Hz), deviceCapture, valid".
inline std::string describe(const TimestampDescriptor& d)
{
    std::string s = toString(d.domain);
    s += " @" + std::to_string(d.ticksPerSecond) + " Hz";
    if (d.nativeTicksPerSecond) s += " (native " + std::to_string(d.nativeTicksPerSecond) + " Hz)";
    s += std::string(", ") + toString(d.semantic) + ", " + toString(d.validity);
    return s;
}

// What can be inferred from a legacy `timestampNs` field written before the
// schema existed. Kept as a documented statement, not an automatic rewrite.
inline const char* legacyTimestampInterpretation()
{
    return "legacy timestampNs: unit/domain undeclared — MindVision recordings hold device "
           "capture ticks x 100000 (0.1 ms ticks -> ns), EGrabber recordings hold Coaxlink "
           "buffer timestamps in microseconds since host boot, mock recordings hold host "
           "steady_clock nanoseconds; treat as Unsupported for cross-clock arithmetic";
}

} // namespace camera::common
