// C++ side of the Rust <-> C++ bridge (epic #246, ADR 0003).
//
// Wraps backend::AppBackend + backend::bridge::BackendFacade behind an opaque
// BackendBridge that cxx owns via UniquePtr. Events emitted from backend threads
// are enqueued (non-blocking) onto an internal mutex-guarded queue and drained
// by Rust via poll_events(). No Qt, no exceptions cross the boundary.
#pragma once

#include "rust/cxx.h"

#include <cstdint>
#include <memory>

namespace mib_bridge {

// Shared structs generated by cxx from src/lib.rs.
struct BridgeCameraDiscovery;
struct BridgeCameraSelection;
struct BridgeCommandResult;
struct BridgeConfigDocument;
struct BridgeProcessingCoreStatus;
struct BridgeAutofocusConfig;
struct BridgeAutofocusStatus;
struct BridgePumpStatus;
struct BridgeReviewMetadata;
struct BridgeReviewMetricsPage;
struct BridgeEvent;
struct BridgeExperimentStatus;
struct BridgeFrame;
struct BridgeMonitoringSnapshot;
struct BridgeProcessingStats;
struct BridgeTriggerStatus;

rust::Vec<BridgeEvent> contract_fixture_events();
BridgeFrame contract_fixture_frame();

class BackendBridge {
public:
    BackendBridge();
    ~BackendBridge();

    BackendBridge(const BackendBridge&) = delete;
    BackendBridge& operator=(const BackendBridge&) = delete;

    bool initialize(rust::Str data_dir);
    void shutdown();
    bool is_initialized() const;

    BridgeCommandResult configure_mock_camera(rust::Str frame_dir,
                                              std::int32_t frame_interval_ms,
                                              bool loop_files);
    BridgeCommandResult start_capture();
    BridgeCommandResult stop_capture();
    BridgeCommandResult start_frame_recording(rust::Str file_path);
    BridgeCommandResult stop_frame_recording();
    BridgeCommandResult playback_seek_latest();
    BridgeCommandResult load_recording(rust::Str file_path);
    BridgeCommandResult playback_seek_index(std::uint64_t frame_index);
    BridgeCommandResult apply_processing(bool realtime_enabled, double pixel_to_micron);
    BridgeCommandResult cancel_operation(std::uint64_t operation_id);
    BridgeCommandResult experiment_start(rust::Str output_path);
    BridgeCommandResult experiment_stop();
    BridgeCommandResult experiment_cancel();
    BridgeExperimentStatus fetch_experiment_status();
    BridgeCommandResult autofocus_connect(std::int32_t com_port, std::int32_t baud_rate,
                                          std::int32_t device_address);
    BridgeCommandResult autofocus_disconnect();
    BridgeCommandResult autofocus_set_enabled(bool enabled);
    BridgeCommandResult autofocus_jog(bool up);
    BridgeCommandResult autofocus_set_config(BridgeAutofocusConfig config);
    BridgeAutofocusStatus fetch_autofocus_status();
    BridgeAutofocusConfig fetch_autofocus_config();
    BridgeCommandResult pump_connect(std::uint32_t pump, std::int32_t com_port,
                                     std::int32_t baud_rate, std::int32_t modbus_address);
    BridgeCommandResult pump_disconnect(std::uint32_t pump);
    BridgeCommandResult pump_set_flow_rate(std::uint32_t pump, double rate, std::int32_t unit);
    BridgeCommandResult pump_set_direction(std::uint32_t pump, std::uint32_t direction);
    BridgeCommandResult pump_start(std::uint32_t pump);
    BridgeCommandResult pump_stop(std::uint32_t pump);
    BridgeCommandResult pump_purge(std::uint32_t pump, std::uint32_t direction);
    BridgeCommandResult pump_stop_purge(std::uint32_t pump);
    BridgeCommandResult pump_set_syringe_volume(std::uint32_t pump, std::int32_t volume,
                                                std::int32_t unit);
    BridgeCommandResult pump_poll_status(std::uint32_t pump);
    BridgePumpStatus fetch_pump_status(std::uint32_t pump);
    BridgeCommandResult pump_scan_addresses(std::int32_t com_port, std::int32_t baud_rate,
                                            std::int32_t start_address, std::int32_t end_address,
                                            std::int32_t timeout_ms);
    BridgeReviewMetadata fetch_review_metadata();
    BridgeReviewMetricsPage fetch_review_metrics_page(bool valid, std::uint64_t offset,
                                                      std::uint64_t count);
    BridgeFrame fetch_review_image(std::uint32_t dataset, std::uint64_t index);
    BridgeCommandResult review_export_csv(rust::Str output_path);
    BridgeConfigDocument fetch_processing_config_json();
    BridgeCommandResult apply_processing_config_json(rust::Str json);
    BridgeCommandResult set_processing_roi(std::int32_t x, std::int32_t y,
                                           std::int32_t w, std::int32_t h);
    BridgeFrame fetch_background_image();
    BridgeCommandResult set_background_image(std::uint64_t width, std::uint64_t height,
                                             rust::Slice<const std::uint8_t> data);
    BridgeCommandResult clear_background_image();
    BridgeProcessingCoreStatus fetch_processing_core_status();
    BridgeCameraDiscovery fetch_camera_discovery();
    BridgeCameraSelection fetch_camera_selection();
    BridgeCommandResult select_hardware_camera(std::int32_t interface_index,
                                               std::int32_t device_index,
                                               rust::Str label);
    BridgeCommandResult select_mindvision_camera(std::int32_t camera_index,
                                                 rust::Str label,
                                                 rust::Str config_path);
    BridgeCommandResult apply_camera_script(rust::Str script_path);
    BridgeCommandResult reset_hardware_camera();
    BridgeCommandResult monitoring_set_active(bool active);
    BridgeCommandResult monitoring_clear();
    BridgeMonitoringSnapshot fetch_monitoring_snapshot(std::uint64_t max_rows);
    BridgeCommandResult trigger_set_pulse_duration(std::int32_t pulse_us);
    BridgeCommandResult trigger_manual_pulse();
    BridgeCommandResult trigger_periodic_start(std::int32_t interval_ms);
    BridgeCommandResult trigger_periodic_stop();
    BridgeTriggerStatus fetch_trigger_status();

    rust::Vec<BridgeEvent> poll_events();
    std::uint64_t queue_overflow_total() const;
    BridgeFrame fetch_latest_frame();
    BridgeFrame fetch_frame_by_index(std::uint64_t frame_index);
    BridgeProcessingStats fetch_processing_stats();

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

std::unique_ptr<BackendBridge> new_backend_bridge();
std::uint32_t bridge_abi_version();

} // namespace mib_bridge
