// GENERATED by scripts/gen_bridge_contract.py from
// crates/mib-bridge/contract/review-contract.json — do not edit by hand.
// YOFO Review's own contract (ADR 0014); the MIB Studio bridge contract is
// ../bridgeContract.ts.

export const REVIEW_ABI_VERSION = 1;

export const OVERLAY_MODES = {
  None: 0,
  AllContour: 1,
  OuterInnerColorCoded: 2,
  AllMask: 3,
  FilteredMask: 4,
} as const;

export const REVIEW_OPERATION_KINDS = {
  ExportMetrics: 0,
  ExportAll: 1,
  BatchExport: 2,
  RegenerateMasks: 3,
  ComputeCore: 4,
  Density: 5,
  ExportCharts: 6,
} as const;

export const REVIEW_REGENERATE_SOURCES = {
  CurrentValid: 0,
  CurrentInvalid: 1,
  WholeFile: 2,
  Avi: 3,
  Folder: 4,
} as const;

export const REVIEW_DENSITY = {
  "level_count": 8,
  "grid_above_points": 5000,
  "sample_seed": 20260924,
  "grid_nx": 256,
  "grid_ny": 128,
  "ramp_rgb": [
    [
      134,
      182,
      239
    ],
    [
      109,
      167,
      236
    ],
    [
      85,
      152,
      231
    ],
    [
      57,
      135,
      229
    ],
    [
      42,
      120,
      214
    ],
    [
      37,
      106,
      191
    ],
    [
      28,
      92,
      171
    ],
    [
      24,
      79,
      149
    ],
    [
      16,
      66,
      129
    ],
    [
      13,
      54,
      107
    ]
  ],
  "ramp_semantics": "backend/processing/MonitoringDensity.h densityRampColor: linear interpolation over the stops, t in [0,1]; level k of n uses t = k/(n-1) (kdeLevelColor)"
} as const;

export const REVIEW_PIXEL_FORMATS = {
  "Mono8": 0,
  "Rgb8": 35127316
} as const;

export const REVIEW_FRAME_PACKET = {
  "base": "bridge-contract.json frame_packet: the same magic, version, header layout, byte order and limits",
  "pull_kinds": {
    "review": 3,
    "review_thumbnails": 5,
    "review_series": 6
  },
  "pixel_formats": {
    "mono8_legacy": 0,
    "mono8": 17301505,
    "rgb8": 35127316
  },
  "identity_semantics": "capture_session and store_generation are zero: review frames come from a recorded file, not a capture",
  "rgb8_semantics": "review pulls (kinds 3, 5, 6) may carry RGB8 (3 bytes per pixel, stride = width*3) when the backend composed an overlay or ROI; mono pulls are unchanged",
  "thumbnail_strip_semantics": "pull kind 5 packs count tiles of size x size as one frame of width size and height size*count; frame_index = page offset"
} as const;
