// @vitest-environment jsdom
import {act} from "react";import {createRoot,Root} from "react-dom/client";import {beforeEach,afterEach,it,expect,vi} from "vitest";
import {invoke} from "@tauri-apps/api/core";import {open,confirm} from "@tauri-apps/plugin-dialog";import {ApplicationUpdateControls} from "./applicationUpdate";
vi.mock("@tauri-apps/api/core",()=>({invoke:vi.fn()}));vi.mock("@tauri-apps/plugin-dialog",()=>({open:vi.fn(),confirm:vi.fn()}));vi.mock("@tauri-apps/plugin-opener",()=>({openUrl:vi.fn()}));Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
let root:Root,host:HTMLDivElement,blocked=false;const busy=vi.fn();
function App(){return <ApplicationUpdateControls channel="stable" blocked={blocked} onBusy={busy}/>;}
async function click(text:string){await act(async()=>Array.from(host.querySelectorAll("button")).find(b=>b.textContent===text)!.click());}
beforeEach(async()=>{vi.resetAllMocks();blocked=false;vi.mocked(invoke).mockResolvedValue({token:"checked-native-token",version:"9.0.0",os:"linux",arch:"x86_64",url:"https://updates.yofo.bio/app.deb",installer_size_bytes:7});vi.mocked(open).mockResolvedValue("/download/app.deb");vi.mocked(confirm).mockResolvedValue(true);host=document.createElement("div");root=createRoot(host);await act(async()=>root.render(<App/>));});afterEach(async()=>{await act(async()=>root.unmount());});
it("requires verification and explicit confirmation before native launch",async()=>{await click("Check Tauri App Releases");expect(Array.from(host.querySelectorAll("button")).find(b=>b.textContent==="Launch Verified Installer…")!.disabled).toBe(true);await click("Verify Downloaded Installer…");expect(invoke).toHaveBeenCalledWith("verify_tauri_app_installer",{token:"checked-native-token",path:"/download/app.deb",uiIdle:true});vi.mocked(confirm).mockResolvedValue(false);await click("Launch Verified Installer…");expect(vi.mocked(invoke).mock.calls.some(([name])=>name==="launch_tauri_app_installer")).toBe(false);vi.mocked(confirm).mockResolvedValue(true);await click("Launch Verified Installer…");expect(invoke).toHaveBeenCalledWith("launch_tauri_app_installer",{token:"checked-native-token",uiIdle:true,confirmed:true});expect(host.textContent).toContain("Installation completion has not been confirmed");});
it("dirty or active UI blocks checks and installer actions",async()=>{blocked=true;await act(async()=>root.render(<App/>));await click("Check Tauri App Releases");expect(invoke).not.toHaveBeenCalled();});
it("rechecks dirty/active state after an asynchronous installer picker",async()=>{await click("Check Tauri App Releases");let finish!:(v:string)=>void;vi.mocked(open).mockImplementation(()=>new Promise(r=>{finish=r;}));await click("Verify Downloaded Installer…");blocked=true;await act(async()=>root.render(<App/>));await act(async()=>finish("/download/app.deb"));expect(vi.mocked(invoke).mock.calls.some(([name])=>name==="verify_tauri_app_installer")).toBe(false);expect(host.textContent).toContain("UI state changed");});
it("tamper or launch failure is shown without exiting",async()=>{await click("Check Tauri App Releases");vi.mocked(invoke).mockRejectedValue(new Error("SHA256 mismatch"));await click("Verify Downloaded Installer…");expect(host.textContent).toContain("SHA256 mismatch");expect(Array.from(host.querySelectorAll("button")).find(b=>b.textContent==="Launch Verified Installer…")!.disabled).toBe(true);});

it("cache cleanup needs confirmation, invalidates verification, and reports locked files",async()=>{await click("Check Tauri App Releases");await click("Verify Downloaded Installer…");vi.mocked(confirm).mockResolvedValue(false);await click("Clear Installer Cache…");expect(vi.mocked(invoke).mock.calls.some(([name])=>name==="clear_tauri_installer_cache")).toBe(false);vi.mocked(confirm).mockResolvedValue(true);vi.mocked(invoke).mockResolvedValue({removed:2,failed:["fixture.exe: locked"]});await click("Clear Installer Cache…");expect(invoke).toHaveBeenCalledWith("clear_tauri_installer_cache",{uiIdle:true,confirmed:true});expect(host.textContent).toContain("Removed 2");expect(host.textContent).toContain("fixture.exe: locked");expect(host.textContent).not.toContain("Launch Verified Installer");});
it("cache cleanup rechecks activity after confirmation",async()=>{let finish!:(value:boolean)=>void;vi.mocked(confirm).mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));await click("Clear Installer Cache…");blocked=true;await act(async()=>root.render(<App/>));await act(async()=>finish(true));expect(invoke).not.toHaveBeenCalled();expect(host.textContent).toContain("Finish pending work");});
