// @vitest-environment jsdom
import {act} from "react";import {createRoot,Root} from "react-dom/client";import {beforeEach,afterEach,it,expect} from "vitest";import {useLiveConfigDraft} from "./liveConfigDraft";import {previewIntervalMs} from "./previewPacing";
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});let root:Root,host:HTMLDivElement,draft:ReturnType<typeof useLiveConfigDraft>;
function Harness(){draft=useLiveConfigDraft();return <textarea value={draft.text} readOnly/>;}
beforeEach(async()=>{host=document.createElement("div");root=createRoot(host);await act(async()=>root.render(<Harness/>));await act(async()=>draft.acceptRemote("original"));});afterEach(async()=>{await act(async()=>root.unmount());});
it("background refresh retains dirty text and exposes changed runtime",async()=>{await act(async()=>draft.edit("operator edits"));await act(async()=>draft.acceptRemote("background changed"));expect(draft.text).toBe("operator edits");expect(draft.dirty).toBe(true);expect(draft.runtimeChanged).toBe(true);});
it("explicit reload cannot erase edits made while its fetch was pending",async()=>{const token=draft.generation();await act(async()=>draft.edit("newer"));await act(async()=>draft.acceptRemote("late response",true,token));expect(draft.text).toBe("newer");await act(async()=>draft.acceptRemote("confirmed reload",true,draft.generation()));expect(draft.dirty).toBe(false);expect(draft.text).toBe("confirmed reload");});
it("a successful old submission cannot clear newer changes",async()=>{await act(async()=>draft.edit("submitted"));await act(async()=>draft.edit("newer"));await act(async()=>draft.applied("submitted"));expect(draft.dirty).toBe(true);await act(async()=>draft.applied("newer"));await act(async()=>draft.acceptRemote("verified server"));expect(draft.text).toBe("verified server");expect(draft.dirty).toBe(false);});
it("profile display rate controls preview requests within safe pacing bounds",()=>{expect(previewIntervalMs(60)).toBeCloseTo(1000/60);expect(previewIntervalMs(15)).toBeCloseTo(1000/15);expect(previewIntervalMs(NaN)).toBeCloseTo(1000/30);expect(previewIntervalMs(1000)).toBeCloseTo(1000/240);});

it("blocks preserved stale edits until explicit reload and rejects late successful apply",async()=>{await act(async()=>draft.edit("operator changes"));expect(draft.canApply()).toBe(true);await act(async()=>draft.acceptRemote("profile applied"));expect(draft.canApply()).toBe(false);await act(async()=>draft.applied("operator changes"));expect(draft.text).toBe("operator changes");expect(draft.dirty).toBe(true);expect(draft.canApply()).toBe(false);await act(async()=>draft.edit("retyped stale edit"));expect(draft.canApply()).toBe(false);await act(async()=>draft.acceptRemote("profile applied",true,draft.generation()));expect(draft.canApply()).toBe(true);await act(async()=>draft.edit("reconciled edit"));expect(draft.canApply()).toBe(true);});
