#!/usr/bin/env python3
"""
Export metrics and images from MIB Studio HDF5 files.

This script reads HDF5 files generated by the MIB Studio application and exports
metrics (and optionally images) in the same format as the existing C++ export functions.

Usage:
    # Export CSV metrics only
    python scripts/export_hdf5.py -i experiment.h5 -o ./export --format csv

    # Export gold-standard metrics JSON (docs/gold_standard_metrics.schema.json)
    python scripts/export_hdf5.py -i experiment.h5 -o ./export --format json

    # Export CSV + images
    python scripts/export_hdf5.py -i experiment.h5 -o ./export --format all

    # Export only valid frames
    python scripts/export_hdf5.py -i experiment.h5 -o ./export --format all --frame-type valid

Dependencies:
    - h5py: HDF5 file reading
    - numpy: Array handling
    - opencv-python (cv2): Image export (if exporting images)

Install dependencies:
    pip install h5py numpy opencv-python
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Schema version for the gold-standard metrics JSON document
# (docs/gold_standard_metrics.schema.json). Bump alongside the schema file
# whenever the frame field set changes; see docs/gold_standard_metrics.md.
GOLD_STANDARD_SCHEMA_VERSION = 1

try:
    import h5py
    import numpy as np
except ImportError as e:
    h5py = None
    np = None
    HDF5_IMPORT_ERROR = e
    HAS_HDF5_DEPS = False
else:
    HDF5_IMPORT_ERROR = None
    HAS_HDF5_DEPS = True


# Try to import cv2 only if needed for image export
try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False


def source_base_name(input_path: Path) -> str:
    """Return the HDF5 source filename without only its final suffix."""
    base = input_path.stem.strip()
    return base if base else "hdf_export"


def unique_path(parent_dir: Path, first_name: str, numbered_pattern: str) -> Path:
    """Return a deterministic non-existing path under parent_dir.

    Issue #344: the candidate is chosen from one directory listing
    (``max existing suffix + 1``) instead of probing ``_2``, ``_3``, ... with
    ``exists()`` per candidate, so the cost does not grow with the number of
    prior exports in ``parent_dir``.
    """
    from hdf_export_engine import next_available_name  # local import: engine depends on this module

    return next_available_name(parent_dir, first_name, numbered_pattern)


def validate_output_root(output_root: Path) -> Tuple[bool, str]:
    """Validate that --output is an output directory path, not a file path."""
    if output_root.suffix.lower() == ".csv":
        return False, f"Output path must be a directory, not a CSV file: {output_root}"

    if output_root.exists() and not output_root.is_dir():
        return False, f"Output path exists and is not a directory: {output_root}"

    return True, ""


def ensure_output_root(output_root: Path) -> Tuple[bool, str]:
    """Create the output root if needed after validating directory semantics."""
    valid, error = validate_output_root(output_root)
    if not valid:
        return False, error

    try:
        output_root.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        return False, f"Failed to create output directory {output_root}: {e}"

    return True, ""


def metrics_csv_path(input_path: Path, output_root: Path) -> Path:
    """Return the collision-safe CSV path for a metrics-only export."""
    base = source_base_name(input_path)
    return unique_path(
        output_root,
        f"{base}_metrics.csv",
        f"{base}_metrics_{{suffix}}.csv",
    )


def metrics_json_path(input_path: Path, output_root: Path) -> Path:
    """Return the collision-safe gold-standard JSON path for a metrics-only export."""
    base = source_base_name(input_path)
    return unique_path(
        output_root,
        f"{base}_metrics.json",
        f"{base}_metrics_{{suffix}}.json",
    )


def export_folder_path(input_path: Path, output_root: Path) -> Path:
    """Return the collision-safe source-specific folder path for image/all exports."""
    base = source_base_name(input_path)
    return unique_path(output_root, base, f"{base}_{{suffix}}")


def resolve_export_targets(input_path: Path, output_root: Path, format_type: str) -> Tuple[Optional[Path], Path]:
    """Resolve generated output paths for the selected export format."""
    if format_type == "csv":
        return metrics_csv_path(input_path, output_root), output_root

    if format_type == "json":
        return metrics_json_path(input_path, output_root), output_root

    data_output_dir = export_folder_path(input_path, output_root)
    csv_path = data_output_dir / "metrics.csv" if format_type == "all" else None
    return csv_path, data_output_dir


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Export metrics and images from MIB Studio HDF5 files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        "--input", "-i",
        type=str,
        required=True,
        help="Path to input .h5 file"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        required=True,
        help="Output directory"
    )
    parser.add_argument(
        "--format", "-f",
        type=str,
        choices=["csv", "json", "images", "all"],
        default="csv",
        help=(
            "Export format: csv (metrics only), json (gold-standard metrics "
            "JSON per docs/gold_standard_metrics.schema.json), images "
            "(images only), or all (csv + images). Default: csv"
        )
    )
    parser.add_argument(
        "--pixel-to-micron", "-p",
        type=float,
        default=0.4886,
        help="Pixel to micron conversion factor. Default: 0.4886"
    )
    parser.add_argument(
        "--frame-type", "-t",
        type=str,
        choices=["valid", "invalid", "both"],
        default="both",
        help="Export valid, invalid, or both frame types. Default: both"
    )
    return parser.parse_args()


def read_hdf5_metadata(h5_file: h5py.File, dataset_path: str) -> Optional[np.ndarray]:
    """
    Read metadata from HDF5 compound datatype dataset.
    
    Args:
        h5_file: Open HDF5 file handle
        dataset_path: Path to metadata dataset (e.g., "/valid_frames/metadata")
        
    Returns:
        Structured numpy array with metadata, or None if dataset doesn't exist
    """
    if dataset_path not in h5_file:
        return None
    
    dataset = h5_file[dataset_path]
    return dataset[:]  # Read entire dataset into memory


def metadata_value(row: np.void, field: str, default):
    names = row.dtype.names or ()
    return row[field] if field in names else default


def metadata_has(row: np.void, field: str) -> bool:
    """Return whether an HDF5 compound metadata row carries ``field``."""
    return field in (row.dtype.names or ())


def read_hdf5_images(h5_file: h5py.File, dataset_path: str) -> Optional[np.ndarray]:
    """
    Read images from HDF5 dataset.
    
    Args:
        h5_file: Open HDF5 file handle
        dataset_path: Path to images dataset (e.g., "/valid_frames/images")
        
    Returns:
        Numpy array of images with shape (num_frames, height, width, channels), or None if dataset doesn't exist

    NOTE (issue #344): this materializes the complete dataset. The CLI and GUI
    exporters no longer use it (they stream one frame at a time through
    ``hdf_export_engine``); it remains for small offline tools such as
    ``reanalyse_hdf5.py``.
    """
    if dataset_path not in h5_file:
        return None
    
    dataset = h5_file[dataset_path]
    return dataset[:]  # Read entire dataset into memory


def read_experiment_info(h5_file: h5py.File) -> Optional[dict]:
    """
    Read experiment info attributes from HDF5 file.
    
    Args:
        h5_file: Open HDF5 file handle
        
    Returns:
        Dictionary with experiment info, or None if group doesn't exist
    """
    if "/experiment_info" not in h5_file:
        return None
    
    info_group = h5_file["/experiment_info"]
    info = {}
    
    # Read available attributes
    for attr_name in info_group.attrs:
        info[attr_name] = info_group.attrs[attr_name]
    
    return info if info else None


def export_metrics_to_csv(
    metadata_valid: Optional[np.ndarray],
    metadata_invalid: Optional[np.ndarray],
    output_path: Path,
    pixel_to_micron: float,
    frame_type: str
) -> Tuple[int, int]:
    """
    Export metrics to CSV file matching the C++ export format.
    
    Args:
        metadata_valid: Valid frames metadata array, or None
        metadata_invalid: Invalid frames metadata array, or None
        output_path: Path to output CSV file
        pixel_to_micron: Pixel to micron conversion factor
        frame_type: "valid", "invalid", or "both"
        
    Returns:
        Tuple of (valid_count, invalid_count) frames exported
    """
    area_conversion_factor = pixel_to_micron * pixel_to_micron
    
    with open(output_path, 'w', encoding='utf-8') as f:
        # Write CSV header (matching C++ format exactly)
        f.write("Frame Type,Index,Timestamp,Object Id,Object Count,Deformability,Area,Area (um²),Area Ratio,Ring Ratio,")
        f.write("Valid,Touches Border,Single Inner,In Range,Inner Count,")
        f.write("Bright Q1,Bright Q2,Bright Q3,Bright Q4\n")
        
        valid_count = 0
        invalid_count = 0
        
        # Export valid frames
        if metadata_valid is not None and frame_type in ("valid", "both"):
            for row in metadata_valid:
                area_microns = row['area'] * area_conversion_factor
                f.write("Valid,")
                f.write(f"{row['index']},")
                f.write(f"{row['timestampNs']},")
                f.write(f"{metadata_value(row, 'objectId', -1)},")
                f.write(f"{metadata_value(row, 'objectCount', 0)},")
                f.write(f"{row['deformability']:.3f},")
                f.write(f"{row['area']:.2f},")
                f.write(f"{area_microns:.2f},")
                f.write(f"{row['areaRatio']:.3f},")
                f.write(f"{row['ringRatio']:.3f},")
                f.write("Yes," if row['isValid'] else "No,")
                f.write("Yes," if row['touchesBorder'] else "No,")
                f.write("Yes," if row['hasSingleInnerContour'] else "No,")
                f.write("Yes," if row['inRange'] else "No,")
                f.write(f"{row['innerContourCount']},")
                f.write(f"{row['brightness_q1']:.2f},")
                f.write(f"{row['brightness_q2']:.2f},")
                f.write(f"{row['brightness_q3']:.2f},")
                f.write(f"{row['brightness_q4']:.2f}\n")
                valid_count += 1
        
        # Export invalid frames
        if metadata_invalid is not None and frame_type in ("invalid", "both"):
            for row in metadata_invalid:
                area_microns = row['area'] * area_conversion_factor
                f.write("Invalid,")
                f.write(f"{row['index']},")
                f.write(f"{row['timestampNs']},")
                f.write(f"{metadata_value(row, 'objectId', -1)},")
                f.write(f"{metadata_value(row, 'objectCount', 0)},")
                f.write(f"{row['deformability']:.3f},")
                f.write(f"{row['area']:.2f},")
                f.write(f"{area_microns:.2f},")
                f.write(f"{row['areaRatio']:.3f},")
                f.write(f"{row['ringRatio']:.3f},")
                f.write("Yes," if row['isValid'] else "No,")
                f.write("Yes," if row['touchesBorder'] else "No,")
                f.write("Yes," if row['hasSingleInnerContour'] else "No,")
                f.write("Yes," if row['inRange'] else "No,")
                f.write(f"{row['innerContourCount']},")
                f.write(f"{row['brightness_q1']:.2f},")
                f.write(f"{row['brightness_q2']:.2f},")
                f.write(f"{row['brightness_q3']:.2f},")
                f.write(f"{row['brightness_q4']:.2f}\n")
                invalid_count += 1

    return valid_count, invalid_count


def _frame_to_gold_standard_dict(row: "np.void", frame_type: str, pixel_to_micron: float) -> Dict[str, Any]:
    """Map one metadata row to a gold-standard JSON frame object (schema v1)."""
    area = float(row['area'])
    document: Dict[str, Any] = {
        "frame_type": frame_type,
        "index": int(row['index']),
        "timestamp_ns": int(row['timestampNs']),
        "object_id": int(metadata_value(row, 'objectId', -1)),
        "object_count": int(metadata_value(row, 'objectCount', 0)),
        "deformability": float(row['deformability']),
        "area": area,
        "area_um2": area * pixel_to_micron * pixel_to_micron,
        "area_ratio": float(row['areaRatio']),
        "ring_ratio": float(row['ringRatio']),
        "is_valid": bool(row['isValid']),
        "touches_border": bool(row['touchesBorder']),
        "has_single_inner_contour": bool(row['hasSingleInnerContour']),
        "in_range": bool(row['inRange']),
        "inner_contour_count": int(row['innerContourCount']),
        "brightness_q1": float(row['brightness_q1']),
        "brightness_q2": float(row['brightness_q2']),
        "brightness_q3": float(row['brightness_q3']),
        "brightness_q4": float(row['brightness_q4']),
    }
    # youngsModulus is only present in HDF5 metadata written by newer builds;
    # omit (rather than emit non-JSON NaN) when absent or out of LUT coverage.
    youngs_modulus = float(metadata_value(row, 'youngsModulus', float('nan')))
    if youngs_modulus == youngs_modulus:  # not NaN
        document["youngs_modulus"] = youngs_modulus
    if metadata_has(row, "isTargetGroup"):
        document["is_target_group"] = bool(row["isTargetGroup"])
    if metadata_has(row, "trackId"):
        document["track_id"] = int(row["trackId"])
        document["track_first_frame"] = int(metadata_value(row, "trackFirstFrame", 0))
        document["track_last_frame"] = int(metadata_value(row, "trackLastFrame", 0))
        document["track_observation_count"] = int(metadata_value(row, "trackObservationCount", 0))
    return document


def export_metrics_to_json(
    metadata_valid: Optional[np.ndarray],
    metadata_invalid: Optional[np.ndarray],
    output_path: Path,
    pixel_to_micron: float,
    frame_type: str,
    source_label: str,
) -> Tuple[int, int]:
    """
    Export metrics to gold-standard JSON matching
    docs/gold_standard_metrics.schema.json (the portable processing contract).

    Args:
        metadata_valid: Valid frames metadata array, or None
        metadata_invalid: Invalid frames metadata array, or None
        output_path: Path to output JSON file
        pixel_to_micron: Pixel to micron conversion factor
        frame_type: "valid", "invalid", or "both"
        source_label: Value for the document's "source" field

    Returns:
        Tuple of (valid_count, invalid_count) frames exported
    """
    frames: List[Dict[str, Any]] = []
    valid_count = 0
    invalid_count = 0

    if metadata_valid is not None and frame_type in ("valid", "both"):
        for row in metadata_valid:
            frames.append(_frame_to_gold_standard_dict(row, "valid", pixel_to_micron))
            valid_count += 1

    if metadata_invalid is not None and frame_type in ("invalid", "both"):
        for row in metadata_invalid:
            frames.append(_frame_to_gold_standard_dict(row, "invalid", pixel_to_micron))
            invalid_count += 1

    document = {
        "version": GOLD_STANDARD_SCHEMA_VERSION,
        "contract_version": GOLD_STANDARD_SCHEMA_VERSION,
        "pixel_to_micron": pixel_to_micron,
        "source": source_label,
        "frames": frames,
    }
    output_path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    return valid_count, invalid_count


def export_images_to_tiff(
    images: np.ndarray,
    metadata: np.ndarray,
    output_dir: Path,
    frame_type_prefix: str
) -> int:
    """
    Export images to TIFF files.

    Args:
        images: Image array with shape (num_frames, height, width, channels)
        metadata: Metadata array with index field
        output_dir: Output directory
        frame_type_prefix: Prefix for filenames ("valid" or "invalid")

    Returns:
        Number of images exported
    """
    if not HAS_CV2:
        print("ERROR: opencv-python (cv2) is required for image export.", file=sys.stderr)
        print("Install with: pip install opencv-python", file=sys.stderr)
        return 0

    exported_count = 0

    for i, image in enumerate(images):
        # Get frame index from metadata
        frame_index = metadata[i]['index']

        # Generate filename: valid_frame_XXXXXX.tiff or invalid_frame_XXXXXX.tiff
        filename = f"{frame_type_prefix}_frame_{frame_index:06d}.tiff"
        filepath = output_dir / filename

        image_bgr = _prepare_image_for_tiff(image, i)
        if image_bgr is None:
            continue

        # Write TIFF without compression (matching C++ behavior)
        if cv2.imwrite(str(filepath), image_bgr):
            exported_count += 1
        else:
            print(f"WARNING: Failed to write image {filepath}", file=sys.stderr)

    return exported_count


def export_series_images_to_tiff(
    h5_file: h5py.File,
    metadata: np.ndarray,
    output_dir: Path
) -> int:
    """
    Export multi-image series data from /valid_frames/series_images.

    The series_images dataset is 4D: (N, seriesCount, H, W).
    Each record produces seriesCount TIFF files.

    Args:
        h5_file: Open HDF5 file handle
        metadata: Valid frames metadata array
        output_dir: Output directory

    Returns:
        Number of series images exported
    """
    if not HAS_CV2:
        return 0

    dataset_path = "/valid_frames/series_images"
    if dataset_path not in h5_file:
        return 0

    series_ds = h5_file[dataset_path]
    if len(series_ds.shape) != 4:
        print(f"WARNING: series_images has unexpected shape {series_ds.shape}", file=sys.stderr)
        return 0

    n_records, series_count, height, width = series_ds.shape
    print(f"Found series_images: {n_records} records x {series_count} images ({height}x{width})")

    exported_count = 0
    for i in range(min(n_records, len(metadata))):
        frame_index = metadata[i]['index']
        series_data = series_ds[i]  # shape: (seriesCount, H, W)

        for s in range(series_count):
            image = series_data[s]
            filename = f"valid_frame_{frame_index:06d}_series_{s:02d}.tiff"
            filepath = output_dir / filename

            image_out = _prepare_image_for_tiff(image, i)
            if image_out is not None and cv2.imwrite(str(filepath), image_out):
                exported_count += 1

    return exported_count


def _prepare_image_for_tiff(image: np.ndarray, index: int) -> Optional[np.ndarray]:
    """Convert an image array to a format suitable for cv2.imwrite."""
    # Ensure image is in correct format (uint8, BGR for OpenCV)
    if image.dtype != np.uint8:
        if image.max() > 255:
            image = (image / image.max() * 255).astype(np.uint8)
        else:
            image = image.astype(np.uint8)

    if len(image.shape) == 2:
        return image
    elif len(image.shape) == 3:
        if image.shape[2] == 1:
            return image[:, :, 0]
        elif image.shape[2] == 3:
            return image
        elif image.shape[2] == 4:
            return cv2.cvtColor(image, cv2.COLOR_RGBA2BGR)
        else:
            print(f"WARNING: Unexpected image shape {image.shape} at index {index}, skipping", file=sys.stderr)
            return None
    else:
        print(f"WARNING: Unexpected image shape {image.shape} at index {index}, skipping", file=sys.stderr)
        return None


def export_hdf5(
    input_path: Path,
    output_dir: Path,
    format_type: str = "csv",
    frame_type: str = "both",
    pixel_to_micron: float = 0.4886
) -> int:
    """
    Export HDF5 data to CSV and/or images (CLI adapter over hdf_export_engine).

    Issue #344: images are streamed one frame at a time, the output is
    published transactionally (a failed/cancelled run never leaves a
    normal-looking partial export), and generated names cost one listing.

    Args:
        input_path: Path to input HDF5 file
        output_dir: Output directory
        format_type: "csv", "json", "images", or "all"
        frame_type: "valid", "invalid", or "both"
        pixel_to_micron: Pixel to micron conversion factor

    Returns:
        0 on success, 1 on error
    """
    from hdf_export_engine import ExportJob, ExportState, print_progress, run_export_job

    # Fail fast on an output root that is a file/CSV path before touching deps.
    ok, error = validate_output_root(Path(output_dir))
    if not ok:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    try:
        job = ExportJob(
            input_path=Path(input_path),
            output_root=Path(output_dir),
            format=format_type,
            frame_selection=frame_type,
            pixel_to_micron=pixel_to_micron,
        )
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    result = run_export_job(job, on_progress=print_progress)
    if result.state != ExportState.COMPLETED:
        print(f"ERROR: {result.error}", file=sys.stderr)
        if result.partial_path is not None:
            print(f"Partial output retained at: {result.partial_path}", file=sys.stderr)
        return 1

    if result.experiment_info:
        print("\nExperiment Info:")
        for key, value in sorted(result.experiment_info.items()):
            print(f"  {key}: {value}")
    if job.format.value in ("csv", "all"):
        target = result.final_path if job.format.value == "csv" else (result.final_path / "metrics.csv")
        print(f"CSV file: {target}")
    elif job.format.value == "json":
        print(f"JSON file: {result.final_path}")
    final_output = result.final_path if job.format.value in ("images", "all") else output_dir
    print(f"\nExport complete. Output directory: {final_output}")
    return 0


def main() -> int:
    """Main entry point for command-line interface."""
    args = parse_args()
    
    # Call the main export function
    return export_hdf5(
        Path(args.input),
        Path(args.output),
        args.format,
        args.frame_type,
        args.pixel_to_micron
    )


if __name__ == "__main__":
    sys.exit(main())
