#!/usr/bin/env python3
"""Generate (or verify) the TypeScript bridge-contract mirror.

Source of truth: crates/mib-bridge/contract/bridge-contract.json (BE-1,
issue #271, ADR 0004). This script renders it to desktop/src/bridgeContract.ts
so the TypeScript layer cannot drift silently from the C++/Rust contract.

Usage:
    python3 scripts/gen_bridge_contract.py            # (re)write the TS file
    python3 scripts/gen_bridge_contract.py --check    # CI drift gate: exit 1
                                                      # if the TS file differs

The C++ side is pinned by static_asserts in crates/mib-bridge/src/shim.cpp and
the Rust side by crates/mib-bridge/tests/contract.rs — both against the same
JSON values.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_JSON = REPO_ROOT / "crates/mib-bridge/contract/bridge-contract.json"
OUTPUT_TS = REPO_ROOT / "desktop/src/bridgeContract.ts"
OUTPUT_RS = REPO_ROOT / "desktop/src-tauri/src/frame_packet_contract.rs"

ENUM_GROUPS = [
    ("event_kinds", "EVENT_KINDS"),
    ("frame_ready_sources", "FRAME_READY_SOURCES"),
    ("command_types", "COMMAND_TYPES"),
    ("camera_types", "CAMERA_TYPES"),
    ("camera_selection_modes", "CAMERA_SELECTION_MODES"),
    ("review_image_datasets", "REVIEW_IMAGE_DATASETS"),
    ("pump_ids", "PUMP_IDS"),
    ("pump_run_states", "PUMP_RUN_STATES"),
    ("pump_directions", "PUMP_DIRECTIONS"),
    ("experiment_states", "EXPERIMENT_STATES"),
    ("error_sources", "ERROR_SOURCES"),
    ("operation_kinds", "OPERATION_KINDS"),
    ("operation_states", "OPERATION_STATES"),
    ("camera_states", "CAMERA_STATES"),
    ("recording_states", "RECORDING_STATES"),
]


def render(contract: dict) -> str:
    lines = [
        "// GENERATED FILE — do not edit by hand.",
        "// Source of truth: crates/mib-bridge/contract/bridge-contract.json",
        "// Regenerate with: python3 scripts/gen_bridge_contract.py",
        "// CI verifies this file with: python3 scripts/gen_bridge_contract.py --check",
        "",
        f"export const BRIDGE_ABI_VERSION = {contract['abi_version']};",
        "",
    ]
    for json_key, ts_name in ENUM_GROUPS:
        entries = contract[json_key]
        lines.append(f"export const {ts_name} = {{")
        for name, value in entries.items():
            lines.append(f"  {name}: {value},")
        lines.append("} as const;")
        lines.append("")
    lines.append("export const FRAME_PACKET = " + json.dumps(contract["frame_packet"], indent=2) + " as const;")
    lines.append("")
    for key, name in [("json_transport", "JSON_TRANSPORT"), ("event_payloads", "EVENT_PAYLOADS")]:
        lines.append("export const " + name + " = " + json.dumps(contract[key], indent=2) + " as const;")
        lines.append("")
    # Reverse lookup for event kinds: numeric value -> stable name.
    lines.append("export const EVENT_KIND_NAMES: Readonly<Record<number, string>> = {")
    for name, value in contract["event_kinds"].items():
        lines.append(f"  {value}: \"{name}\",")
    lines.append("};")
    lines.append("")
    lines.append("export type BridgeEventKindName = keyof typeof EVENT_KINDS;")
    lines.append("")
    return "\n".join(lines)


def render_rust(contract: dict) -> str:
    c = contract["frame_packet"]
    fields = [("VERSION", "u16", "version"), ("HEADER_BYTES", "usize", "header_bytes"),
              ("MAX_PAYLOAD_BYTES", "u64", "max_payload_bytes"),
              ("MAX_PIXELS", "u64", "max_pixels"), ("MAX_DIMENSION", "u64", "max_dimension")]
    lines = ["// GENERATED by scripts/gen_bridge_contract.py; do not edit."]
    lines += [f"pub const {name}: {kind} = {c[key]};" for name, kind, key in fields]
    lines += [f"pub const JSON_TRANSPORT_VERSION: u32 = {contract['json_transport']['version']};",
              f"pub const MAX_EVENT_TEXT_BYTES: usize = {contract['json_transport']['max_event_text_bytes']};"]
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    contract = json.loads(CONTRACT_JSON.read_text(encoding="utf-8"))

    # Structural sanity: values inside a group must be unique and contiguous
    # from 0 (the contract is additive-append-only).
    for json_key, _ in ENUM_GROUPS:
        values = sorted(contract[json_key].values())
        if values != list(range(len(values))):
            print(
                f"gen_bridge_contract: {json_key} values must be contiguous "
                f"from 0 (got {values}) — the contract is append-only",
                file=sys.stderr,
            )
            return 1

    outputs = {OUTPUT_TS: render(contract), OUTPUT_RS: render_rust(contract)}
    for path, rendered in outputs.items():
        if check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != rendered:
                print(f"gen_bridge_contract: drift detected in {path.relative_to(REPO_ROOT)}", file=sys.stderr)
                return 1
        else:
            path.write_text(rendered, encoding="utf-8")
    print("gen_bridge_contract: TypeScript and Rust packet contracts " + ("in sync" if check else "generated"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
