# Consolidated test runners (2026-09-09).
#
# Many small test executables cost more link time than they are worth: on the
# bench PC the ~100 backend test binaries summed 345 s of linking (mean 1.8 s,
# up to 7 s each with /DEBUG PDBs) on every header touch, and the 4-core CI
# runner paid that serially. A runner compiles every registered test source
# into ONE executable: each source gets a `main=mib_test_main__<target>`
# compile definition and a generated dispatcher calls the entry named by the
# first argument. CTest entries run `<runner> <target> [args]`, so each test
# still has its own process (signals, _Exit, watchdogs behave as before).
#
#   mib_test_runner_add(<runner> <target> <abs-source>)
#   mib_test_runner_link(<runner> [PRIVATE] <libs>...)      # accumulates
#   mib_test_runner_finalize(<runner> [<extra sources>...])  # defines the target
#
# After finalize, link/set properties on <runner> as on any target. A test
# that cannot share a binary (re-executes argv[0], exits with a file open as
# the test itself, needs add_dependencies on fixtures, is referenced by tools
# or workflows by name) keeps its own add_executable.
#
# Gotcha: MSVC mangles `int main(int, char* argv[])` as (int, char** const)
# and `int main(int, char** argv)` as (int, char**). The dispatcher declares
# each entry in the spelling the test used, otherwise the link fails with an
# unresolved external.

function(mib_test_runner_add runner target source)
    if(NOT IS_ABSOLUTE "${source}")
        message(FATAL_ERROR "mib_test_runner_add(${runner} ${target}): source must be absolute: ${source}")
    endif()
    file(READ "${source}" _code)
    if(_code MATCHES "int[ \t]+main[ \t]*\\([ \t]*int[^)]*\\[[ \t]*\\][ \t]*\\)")
        set(_sig array)
    elseif(_code MATCHES "int[ \t]+main[ \t]*\\([ \t]*int[^)]*\\)")
        set(_sig args)
    else()
        set(_sig noargs)
    endif()
    set_source_files_properties("${source}" PROPERTIES
        COMPILE_DEFINITIONS "main=mib_test_main__${target}")
    set_property(GLOBAL APPEND PROPERTY MIB_TEST_RUNNER_${runner}_ENTRIES "${target}:${_sig}")
    set_property(GLOBAL APPEND PROPERTY MIB_TEST_RUNNER_${runner}_SOURCES "${source}")
endfunction()

function(mib_test_runner_link runner)
    set(_libs ${ARGN})
    list(REMOVE_ITEM _libs PRIVATE PUBLIC INTERFACE)
    set_property(GLOBAL APPEND PROPERTY MIB_TEST_RUNNER_${runner}_LIBS ${_libs})
endfunction()

function(mib_test_runner_finalize runner)
    get_property(_entries GLOBAL PROPERTY MIB_TEST_RUNNER_${runner}_ENTRIES)
    get_property(_sources GLOBAL PROPERTY MIB_TEST_RUNNER_${runner}_SOURCES)
    get_property(_libs GLOBAL PROPERTY MIB_TEST_RUNNER_${runner}_LIBS)
    if(NOT _entries)
        message(FATAL_ERROR "mib_test_runner_finalize(${runner}): no tests registered")
    endif()
    if(_libs)
        list(REMOVE_DUPLICATES _libs)
    endif()
    set(_decl "")
    set(_table "")
    foreach(_e IN LISTS _entries)
        string(REPLACE ":" ";" _parts "${_e}")
        list(GET _parts 0 _name)
        list(GET _parts 1 _sig)
        if(_sig STREQUAL "args")
            string(APPEND _decl "int mib_test_main__${_name}(int, char**);\n")
            string(APPEND _table "    {\"${_name}\", nullptr, &mib_test_main__${_name}},\n")
        elseif(_sig STREQUAL "array")
            string(APPEND _decl "int mib_test_main__${_name}(int, char*[]);\n")
            string(APPEND _table "    {\"${_name}\", nullptr, &mib_test_main__${_name}},\n")
        else()
            string(APPEND _decl "int mib_test_main__${_name}();\n")
            string(APPEND _table "    {\"${_name}\", &mib_test_main__${_name}, nullptr},\n")
        endif()
    endforeach()
    set(_runner_name "${runner}")
    set(_main "${CMAKE_CURRENT_BINARY_DIR}/${runner}_main.cpp")
    file(CONFIGURE OUTPUT "${_main}" @ONLY CONTENT [[
// Generated by cmake/MIBTestRunner.cmake for @_runner_name@.
// One process per CTest entry: `@_runner_name@ <test> [args...]`.
#include <cstdio>
#include <cstring>

@_decl@
namespace {
struct Entry {
    const char* name;
    int (*noargs)();
    int (*args)(int, char**);
};
const Entry kEntries[] = {
@_table@};
} // namespace

int main(int argc, char** argv)
{
    if (argc < 2 || std::strcmp(argv[1], "--list") == 0) {
        std::fprintf(stderr, "usage: %s <test> [args...]\n", argv[0]);
        for (const auto& e : kEntries) std::fprintf(stderr, "  %s\n", e.name);
        return argc < 2 ? 2 : 0;
    }
    for (const auto& e : kEntries) {
        if (std::strcmp(argv[1], e.name) == 0) {
            return e.args ? e.args(argc - 1, argv + 1) : e.noargs();
        }
    }
    std::fprintf(stderr, "@_runner_name@: unknown test '%s'\n", argv[1]);
    return 2;
}
]])
    add_executable(${runner} "${_main}" ${_sources} ${ARGN})
    target_include_directories(${runner} PRIVATE ${PROJECT_SOURCE_DIR}/tests)
    if(_libs)
        target_link_libraries(${runner} PRIVATE ${_libs})
    endif()
    set_target_properties(${runner} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/$<CONFIG>"
    )
    list(LENGTH _entries _n)
    message(STATUS "${runner}: ${_n} tests in one runner")
endfunction()
